---
- src: https://github.com/napalm-automation/napalm-ansible/
  version: master
  name: napalm
  path: roles
#- src: https://github.com/PaloAltoNetworks/ansible-pan/
#  version: master
#  name: ansible-pan
#  path: roles
