---
- set_fact:
    tmp_config: "/tmp/hostname_{{inventory_hostname}}.txt"
    HOSTNAME: "{{inventory_hostname}}-{{HOSTNAME_SUFFIX}}"
    template_name: "hostname/hostname_{{ dev_os }}.j2"

#
# Define source_data because it will be displayed by "run_example" play
#
- set_fact:
    source_data:
      HOSTNAME: "{{ HOSTNAME }}"
      dev_os: "{{ dev_os }}"
      template_name: "{{ template_name }}"

- name: "Set hostname as '{{ HOSTNAME }}'"
  template: >
    src="{{ template_name }}"
    dest="{{ tmp_config }}"

#
# Define examples because it will be displayed by "run_example" play
#
- set_fact:
    examples: {
      'code': "set hostname for different OSes using shared template via include",
      'result': "{{ lookup('file', tmp_config).split('\n') }}"
    }
