---
HOSTNAME_SUFFIX: EXAMPLE

shared_vlans:
  '99999':
    name: fake_vlan
    description: "Just an example - will be filtered out..."

  '999':
    name: bogus
    description: "Bogus vlan - replace Cisco Native VLAN"
    comment: "no IP subnet; only for stripping Cisco Native Vlan"
