---
description: various operations performed on IP address/IP network objects

source_data:
  ip_addr: "10.20.30.43/28"

examples:
  - code: "source_data.ip_addr | ipaddr('netmask')"
    result: "{{ source_data.ip_addr | ipaddr('netmask') }}"
  - code: "source_data.ip_addr | ipaddr('hostmask')"
    result: "{{ source_data.ip_addr | ipaddr('hostmask') }}"
  - code: "source_data.ip_addr | ipaddr('0')"
    comment: "The base subnet that IP address belongs to"
    result: "{{ source_data.ip_addr | ipaddr('0') }}"
  - code: "source_data.ip_addr | ipaddr('5')"
    comment: "5th IP on subnet: treat arithmetic 'NET_BASE_ADDR + 5' as IP"
    result: "{{ source_data.ip_addr | ipaddr('5') }}"
  - code: "source_data.ip_addr | ipaddr('address')"
    result: "{{ source_data.ip_addr | ipaddr('address') }}"
  - code: "source_data.ip_addr | ipaddr('size')"
    result: "{{ source_data.ip_addr | ipaddr('size') }}"
