---
- name: Execute a particular code example
  hosts: all
  connection: local
  gather_facts: no

  roles:
    - { role: describe_examples, when: inventory_hostname == 'help' }
    - { role: run_example,       when: inventory_hostname != 'help' }
